# Full algorithm - generating grocery lists

1. Define variables: days-times-stores
2. Define limits: min amount-max amount
3. Generate (random) lists from narrowed down df

### Import libraries

In [44]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import dataframe_image as dfi
from datetime import time
import matplotlib.dates as mdates
from matplotlib.ticker import StrMethodFormatter
from matplotlib.pyplot import figure
from random import sample

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.colheader_justify', 'center')
pd.set_option('display.precision', 2)

class bcolors:
    WARNING = '\033[91m'
    BOLD = '\033[1m'

In [45]:
    # Function to generate #visits per day of the week
from AlgorithmDAYS_HH2 import beforeNY, AfterNY
    # Function to generate store name (&type) per weekday (+ assign #of visits per day)
from AlgorithmSTORE_HH2 import Mondays, Tuesdays, Wednesdays, Thursdays, Fridays, Saturdays, Sundays
    #Function to define the limits for total visits, days, same store and type per week
from AlgorithmCOUNTS_HH2 import CountTotalVisits, CountTotalDays, CountStoreName, CountStoreType, CountTotalPerday, CountVisitsPerDay
    # Function to decide time (morning, noon. afternoon) per visited store
from AlgorithmTIMES_HH2 import AlbertHeijn, Okay, Delhaize, Carrefour, VersavelPoelman, Sys, Brabo, Ikea, Kruidvat
    # Function to decide amounts per visit & per week
from AlgorithmAMOUNT_HH2 import StoreAmount, WeekAmount, StoreCount, WeekCount

In [46]:
dataframe = pd.read_csv (r"C:\Users\20204113\OneDrive - TU Eindhoven\2_Research\1_Groceries\DATA\9th week - narrative (3rd attempt)\HH2\df\df_HH2.csv")

# Define variables - day/time/store

## Days & visits

In [47]:
CountTotalVisits()

(4, 8)

In [48]:
CountTotalDays()

(2, 5)

In [49]:
i = 0

while i < 2:

    ### 1. What DAY?

        # Select the relevant df for this generated grocery list, comment out the other one
    # df = beforeNY()
    df = AfterNY()

        # identify counts for visits per weekday
    mo = int(df["times"].values[0])
    tu = int(df["times"].values[1])
    we = int (df["times"].values[2])
    th = int (df["times"].values[3])
    fr = int (df["times"].values[4])
    sa = int (df["times"].values[5])
    su = int (df["times"].values[6])
    
        
        ### CHECKPOINT: range for visits/week and days/week
        
        # Check if the total GROCERY VISITS PER WEEK are within the normal range
    visitcount = df['times'].sum()
    totalvisits = CountTotalVisits()
    minvisits = totalvisits[0]
    maxvisits = totalvisits[1]
    if minvisits <= visitcount <= maxvisits:
        i= i+1
    else:
        print(f"{bcolors.WARNING}{bcolors.BOLD} RERUN - Too few/many visits per week")
        i=0
        continue

        # Check if the total GROCERY DAYS PER WEEK are within the normal range
    dayscount = df['times'].nunique()
    totaldays = CountTotalDays()
    mindays = totaldays[0]
    maxdays = totaldays[1]
    if mindays <= dayscount <= maxdays:
        i = i+1
        display(df)
    else:
        print(f"{bcolors.WARNING}{bcolors.BOLD} RERUN - Too few/many days per week")
        i=0
        continue

 RERUN - Too few/many visits per week
 RERUN - Too few/many visits per week

   times    day
4   2.0      Monday
6   0.0     Tuesday
4   0.0   Wednesday
6   1.0    Thursday
4   0.0      Friday
6   1.0    Saturday
4   0.0      Sunday

## Stores & time

In [50]:
restart = True 

while restart:

    ### 2. What STORE?

        # Generate store names for the [previously identified] shopping dags + corresponding store type
    stores = [Mondays(mo), Tuesdays(tu), Wednesdays(we), Thursdays(th), Fridays(fr), Saturdays(sa), Sundays(su)]
        # create one df for all visited stores + day of the week
    stores = pd.concat(stores)


    ### 3. What TIME?

        # Identifier counts for store names per week
    AHt = (stores['store_name'] == 'Albert Heijn').sum()
    OKt = (stores['store_name'] == 'Okay').sum()
    DHt = (stores['store_name'] == 'Delhaize').sum()
    CFt = (stores['store_name'] == 'Carrefour').sum()
    VPt = (stores['store_name'] == 'Versavel Poelman').sum()
    SYt = (stores['store_name'] == 'Sys').sum()
    BRt = (stores['store_name'] == 'Brabo').sum()
    IKt = (stores['store_name'] == 'Ikea').sum()
    KRt = (stores['store_name'] == 'Kruidvat').sum()

        # Generate times per storename and compile in df with stores
    storetimes = [AlbertHeijn(AHt), Okay(OKt), Delhaize(DHt), Carrefour(CFt), VersavelPoelman(VPt), Sys(SYt), Brabo(BRt), Ikea(IKt), Kruidvat(KRt)]
    storetimes = pd.concat(storetimes)
    stores = pd.merge(stores, storetimes, on="store_name")

    ### CHECKPOINT: range for amount of stores per week.day

        # Check if the total STORE TYPES VISITED PER WEEK are within the normal range
    for storetype in dataframe['store_type']:
        typecount = stores[stores['store_type']==storetype]['store_type'].count()
        countstoretype = CountStoreType(storetype)
        minstoretype = countstoretype[0]
        maxstoretype = countstoretype[1]
        if typecount < minstoretype:
            print(f"{bcolors.WARNING}{bcolors.BOLD} RERUN - Too few store type:", storetype)
            restart = True
            break # force restart
        elif maxstoretype < typecount:
            print(f"{bcolors.WARNING}{bcolors.BOLD} RERUN - Too many store type:", storetype)
            restart = True
            break # force restart
        else:
            pass


        # Check if the total STORE NAMES VISITED PER WEEK are within the normal range
    for storename in dataframe['store_name']:
        namecount = stores[stores['store_name']==storename]['store_name'].count()
        countstorename = CountStoreName(storename)
        minstorename = countstorename[0]
        maxstorename = countstorename[1]
        if namecount < minstorename:
            print(f"{bcolors.WARNING}{bcolors.BOLD} RERUN - Too few store name:", storename)
            restart = True
            break # force restart
        elif maxstorename < namecount:
            print(f"{bcolors.WARNING}{bcolors.BOLD} RERUN - Too many store name:", storename)
            restart = True
            break # force restart
        else:
            pass


        # Check if the total STORES VISITED PER DAY are within the normal range
    for day in dataframe['day']:
        perdaycount = stores[stores['day']==day]['day'].count()
        CountTotalPerday = CountVisitsPerDay(day)
        minstoreperday = CountTotalPerday[0]
        maxstoreperday = CountTotalPerday[1]
        if namecount < minstoreperday:
            print(f"{bcolors.WARNING}{bcolors.BOLD} RERUN - Too few stores on:", day)
            restart = True
            break # force restart
        elif maxstoreperday < namecount:
            print(f"{bcolors.WARNING}{bcolors.BOLD} RERUN - Too many stores on:", day)
            restart = True
            break # force restart
        else:
            restart = False
            display(stores)
            break

 RERUN - Too many store type: supermarket
 RERUN - Too many store name: Albert Heijn
 RERUN - Too many stores on: Saturday

      store_name     store_type     day       time
0  Versavel Poelman      butcher    Monday    morning
1               Sys       bakery    Monday    morning
2              Okay  supermarket  Thursday  afternoon
3         Carrefour  supermarket  Saturday  afternoon

## Define limits per week (item counts)

In [51]:
WeekCount()

(31, 98)

In [87]:
storetime = stores[['store_name','time']]
storetime

restart = True 

while restart:
    storecounts = []

    for store, time in storetime.itertuples(index=False):
        storecounts.append(StoreCount(store,time))

    stores['counts'] = storecounts
    
    # Check if the total ITEMS PER STORE are within the normal range
    for items in dataframe['item_type']:
        week9count = stores['counts'].sum()
        NormWeekCount = WeekCount()
        minWeekCount = NormWeekCount[0]
        maxWeekCount = NormWeekCount[1]
        if week9count < minWeekCount:
            print(f"{bcolors.WARNING}{bcolors.BOLD} RERUN - Too few items:", week9count)
            restart = True
            break # force restart
        elif maxWeekCount < week9count:
            print(f"{bcolors.WARNING}{bcolors.BOLD} RERUN - Too many items:", week9count)
            restart = True
            break # force restart
        else:
            restart = False
            display(stores)
            break

      store_name     store_type     day       time     counts
0  Versavel Poelman      butcher    Monday    morning     6
1               Sys       bakery    Monday    morning     1
2              Okay  supermarket  Thursday  afternoon    23
3         Carrefour  supermarket  Saturday  afternoon    31

# The Grocery Lists

In [88]:
df = pd.read_csv (r"C:\Users\20204113\OneDrive - TU Eindhoven\2_Research\1_Groceries\DATA\9th week - narrative (3rd attempt)\HH2\df\df_HH2.csv")

In [89]:
    ## Create dataframes for each day they go shopping
typedf = {}

for storetype in stores['store_type']:
        storeday = df[df['store_type'] == storetype]
        items = storeday[['item_type', 'item_name', 'day', 'store_type','store_name', 'amount']]
        typedf[storetype] = pd.DataFrame(items)
        typedf[storetype].drop_duplicates()


    ## Split up the dataframes to store name for mon, tue, sat, sun
storetypes = stores.store_type.values.tolist()
days = stores.day.values.tolist()           
            
thisdaysdf = {}
daydf = {}

if 'supermarket'in stores.values:
        for day  in days:
            thisdaydf = typedf['supermarket']
            storesdf = thisdaydf[thisdaydf['day'] == day]
            items = storesdf[['item_type', 'item_name', 'day', 'store_type', 'store_name', 'amount']]
            daydf[day] = pd.DataFrame(items)
            daydf[day].drop_duplicates()

In [94]:
    ## Sample the dataframes per day they go shopping
def SupermarketItems():
        dayamount = stores[['day', 'store_type', 'store_name', 'counts']]
        if 'supermarket' in dayamount.values:
                grocerylist = dayamount[dayamount['store_type'] == 'supermarket']
                dayslist = grocerylist.day.values.tolist()
                amounts = grocerylist.counts.values.tolist()
                for amount, day in zip(amounts, dayslist):
                    if 'supermarket' in dayamount.values:
                        daydf[day]= daydf[day].drop_duplicates()
                        return (daydf[day].sample(n=amount, replace=False))
                    else:
                        pass

                    
def StoretypeItems(storetype):                   
        if storetype in dayamount.values:
                grocerylist = dayamount[dayamount['store_type'] == storetype]
                for amount in grocerylist['counts']:
                    if storetype in dayamount.values:
                        typedf[storetype] = typedf[storetype].drop_duplicates()
                        display(typedf[storetype].sample(n=amount, replace=False))
                    else:
                        pass

In [95]:
StoretypeItems('butcher')

     item_type      item_name        day    store_type     store_name     amount
130  charcuterie    chateaubriand  Thursday   butcher              Brabo     1
41   charcuterie      DROGE WORST    Sunday   butcher   Versavel Poelman     1
35   meat spread  PREPARE DU CHEF    Sunday   butcher   Versavel Poelman     1
208  charcuterie         KIPFILET    Monday   butcher   Versavel Poelman     1
38   fish spread    NEPTUNESALADA    Sunday   butcher   Versavel Poelman     1
203  meat spread  PREPARE DU CHEF    Monday   butcher   Versavel Poelman     1
284  meat spread  PREPARE DU CHEF  Saturday   butcher   Versavel Poelman     1

In [91]:
n = stores['store_type'].value_counts()['supermarket']

for _ in range(n):
    display(SupermarketItems())

       item_type                     item_name                    day     store_type    store_name   amount
146      charcuterie                   BREYDEL Breydelham 180g  Thursday  supermarket          Okay     1
148      meat spread                       BONI Kipsalade 175g  Thursday  supermarket          Okay     1
151      meat spread        LUITEN filet americain uitjes 150g  Thursday  supermarket          Okay     1
157  canned cherries    BONI noordkriek ontpit siroop bok 700g  Thursday  supermarket          Okay     2
114          peaches    EVERYDAY halve perzik siroop blik 820g  Thursday  supermarket          Okay     1
115      apple sauce           EVERYDAY appelcompote stuk 710g  Thursday  supermarket          Okay     1
109          chicken          OKAY gebakken kip met saus 1,1kg  Thursday  supermarket          Okay     1
153       pita bread   Boni pitabroodjes voorgebakken 6st 480g  Thursday  supermarket          Okay     1
121           coffee                  BONI Lungo cups UTZ 16st  Thursday  supermarket          Okay     1
369            mints                                    MENTOS  Thursday  supermarket  Albert Heijn     1
145      charcuterie    WEIGHT WATCHERS kipfilet sneetjes 120g  Thursday  supermarket          Okay     1
161      charcuterie             OKAY Ardeens gehaktbrood 500g  Thursday  supermarket          Okay     1
105           cheese            BONI gouda light sneetjes 250g  Thursday  supermarket          Okay     1
159           cheese   BEEMSTERLITE jong belegen sneetjes 250g  Thursday  supermarket          Okay     1
155     coconutdrink                   ALPRO kokosnootdrink 1L  Thursday  supermarket          Okay     1
123   sweet potatoes                BONI zoete aardappel (los)  Thursday  supermarket          Okay     1
163             pork                         OKAY Gyros +-500g  Thursday  supermarket          Okay     1
122       face masks       wegwerp mondmaskers volwassenen 5st  Thursday  supermarket          Okay     1
108         celeriac                          knolselder 1stuk  Thursday  supermarket          Okay     1
156          dessert              ALPRO karamel dessert 4x125g  Thursday  supermarket          Okay     1
103            cream  ALPRO CUISINE soyaroom li 5%vg brik 25cl  Thursday  supermarket          Okay     3
368        egg cakes                                EIERKOEKEN  Thursday  supermarket  Albert Heijn     1
332      lunch salad                         AH MAALTIJDSALADE  Thursday  supermarket  Albert Heijn     1

        item_type                    item_name                    day     store_type    store_name   amount
122        face masks      wegwerp mondmaskers volwassenen 5st  Thursday  supermarket          Okay     1
123    sweet potatoes               BONI zoete aardappel (los)  Thursday  supermarket          Okay     1
151       meat spread       LUITEN filet americain uitjes 150g  Thursday  supermarket          Okay     1
140           dessert        PUR NATUR BIO Panna Cotta 2x125g   Thursday  supermarket          Okay     2
112      french fries                     BELVIVA pom'pin 750g  Thursday  supermarket          Okay     1
126      bell peppers               paprika punt zoet rood Los  Thursday  supermarket          Okay     1
332       lunch salad                        AH MAALTIJDSALADE  Thursday  supermarket  Albert Heijn     1
143            cheese                          PORT SALUT 135g  Thursday  supermarket          Okay     1
115       apple sauce          EVERYDAY appelcompote stuk 710g  Thursday  supermarket          Okay     1
333       fruit salad                              FRUITSALADE  Thursday  supermarket  Albert Heijn     1
148       meat spread                      BONI Kipsalade 175g  Thursday  supermarket          Okay     1
119       pasta sauce   SPAGHERONI pastasaus tradizionale 520g  Thursday  supermarket          Okay     1
104            cheese          BONI Spaghetti Mix geraspt 200g  Thursday  supermarket          Okay     1
370       lunch salad                             AH MLTSALADE  Thursday  supermarket  Albert Heijn     1
154          iced tea        BONI Green Tea niet-bruisend 33cl  Thursday  supermarket          Okay     6
161       charcuterie            OKAY Ardeens gehaktbrood 500g  Thursday  supermarket          Okay     1
120         spaghetti             BONI spaghetti volkoren 500g  Thursday  supermarket          Okay     1
155      coconutdrink                  ALPRO kokosnootdrink 1L  Thursday  supermarket          Okay     1
106  chocolate spread                  RABEKO Choco light 250g  Thursday  supermarket          Okay     1
146       charcuterie                  BREYDEL Breydelham 180g  Thursday  supermarket          Okay     1
107              figs               BONI gedroogde vijgen 500g  Thursday  supermarket          Okay     1
158           cereals    KELLOGG'S TRéSOR choco-hazelnoot 450g  Thursday  supermarket          Okay     1
159            cheese  BEEMSTERLITE jong belegen sneetjes 250g  Thursday  supermarket          Okay     1

In [65]:
    ## Sample the dataframes per day they go shopping
dayamount = stores[['day', 'store_type', 'store_name', 'counts']]

if 'supermarket' in dayamount.values:
        grocerylist = dayamount[dayamount['store_type'] == 'supermarket']
        dayslist = grocerylist.day.values.tolist()
        amounts = grocerylist.counts.values.tolist()
    for amount, day in zip(amounts, dayslist):
        if 'supermarket' in dayamount.values:
            daydf[day]= daydf[day].drop_duplicates()
            display(daydf[day].sample(n=amount, replace=False))
        else:
            pass
        
if 'butcher' in dayamount.values:
        grocerylist = dayamount[dayamount['store_type'] == 'butcher']
    for amount in grocerylist['counts']:
        if 'butcher' in dayamount.values:
            typedf['butcher'] = typedf['butcher'].drop_duplicates()
            display(typedf['butcher'].sample(n=amount, replace=False))
        else:
            pass

if 'bakery' in dayamount.values:
        grocerylist = dayamount[dayamount['store_type'] == 'bakery']
    for amount in grocerylist['counts']:
        if 'bakery' in dayamount.values:
            typedf['bakery'] = typedf['bakery'].drop_duplicates()
            display(typedf['bakery'].sample(n=amount, replace=False))
        else:
            pass

if 'drugstore' in dayamount.values:
        grocerylist = dayamount[dayamount['store_type'] == 'drugstore']
    for amount in grocerylist['counts']:
        if 'drugstore' in dayamount.values:
            typedf['drugstore'] = typedf['drugstore'].drop_duplicates()
            display(typedf['drugstore'].sample(n=amount, replace=False))
        else:
            pass    
        
if 'furniture store' in dayamount.values:
        grocerylist = dayamount[dayamount['store_type'] == 'furniture store']
    for amount in grocerylist['counts']:
        if 'furniture store' in dayamount.values:
            daydf['furniture store'] = daydf['furniture store'].drop_duplicates()
            display(daydf['furniture store'].sample(n=amount, replace=False))
        else:
            pass

        item_type                     item_name                    day     store_type    store_name   amount
104            cheese           BONI Spaghetti Mix geraspt 200g  Thursday  supermarket          Okay     1
154          iced tea         BONI Green Tea niet-bruisend 33cl  Thursday  supermarket          Okay     6
123    sweet potatoes                BONI zoete aardappel (los)  Thursday  supermarket          Okay     1
144  chocolate spread                   RABEKO Choco light 250g  Thursday  supermarket          Okay     2
109           chicken          OKAY gebakken kip met saus 1,1kg  Thursday  supermarket          Okay     1
163              pork                         OKAY Gyros +-500g  Thursday  supermarket          Okay     1
115       apple sauce           EVERYDAY appelcompote stuk 710g  Thursday  supermarket          Okay     1
142           pudding    JOYVALLE pudding griesmeel natuur 135g  Thursday  supermarket          Okay     4
368         egg cakes                                EIERKOEKEN  Thursday  supermarket  Albert Heijn     1
117      coconut milk                  BONI kokosmelk blik 400g  Thursday  supermarket          Okay     2
110     vegetable mix               BONI spaghettigroenten 400g  Thursday  supermarket          Okay     1
107              figs                BONI gedroogde vijgen 500g  Thursday  supermarket          Okay     1
332       lunch salad                         AH MAALTIJDSALADE  Thursday  supermarket  Albert Heijn     1
159            cheese   BEEMSTERLITE jong belegen sneetjes 250g  Thursday  supermarket          Okay     1
160            apples         EVERYDAY Jonagold appelen 6st 1kg  Thursday  supermarket          Okay     1
158           cereals     KELLOGG'S TRéSOR choco-hazelnoot 450g  Thursday  supermarket          Okay     1
105            cheese            BONI gouda light sneetjes 250g  Thursday  supermarket          Okay     1
141           dessert  EVERYDAY dessert liégeois chocolade 200g  Thursday  supermarket          Okay     4
331         chocolate                              MILKA TABLET  Thursday  supermarket  Albert Heijn     1
125              leek                                  prei Los  Thursday  supermarket          Okay     1
369             mints                                    MENTOS  Thursday  supermarket  Albert Heijn     1

        item_type                     item_name                     day     store_type  store_name  amount
25           broccoli                              BROCCOLI 500G  Saturday  supermarket  Carrefour     1
276      bell peppers                 paprika punt zoet rood los  Saturday  supermarket       Okay     1
249              soup       BONI tomatensoep met balletjes 950ml  Saturday  supermarket       Okay     1
252          potatoes     OK POM-PURE vastkokend aardappelen 1kg  Saturday  supermarket       Okay     1
265      frozen fries   MCCAIN country potatoes met kruiden 750g  Saturday  supermarket       Okay     1
29           zucchini                                 COURGETTEN  Saturday  supermarket  Carrefour     1
264   frozen potatoes                    BONI forestiere mix 1kg  Saturday  supermarket       Okay     1
251         pistachio             BONI pistachenoten gepeld 200g  Saturday  supermarket       Okay     1
20           cucumber                                  KOMKOMMER  Saturday  supermarket  Carrefour     1
337          iced tea     BONI Iced Tea Peach niet-bruisend 0,5L  Saturday  supermarket       Okay     6
9         minced meat                          VARKENSKALFGEHAKT  Saturday  supermarket  Carrefour     1
2          chocolates                           M&M'S CRISPY 36G  Saturday  supermarket  Carrefour     1
258            grapes              BONI druiven pitloos mix 500g  Saturday  supermarket       Okay     1
7           egg cakes                        WEV EIERKOEKEN 350G  Saturday  supermarket  Carrefour     1
259             salad           BONI fijnproeversmix Rucola 250g  Saturday  supermarket       Okay     1
271              soup   LIEBIG DELISOUP wortel pomp.bal. brik 1L  Saturday  supermarket       Okay     1
248       charcuterie     BONI Beenham meesterl. Glutenvrij 200g  Saturday  supermarket       Okay     1
6               candy                         ETNA ST NIC GUIM C  Saturday  supermarket  Carrefour     1
335             pizza              BONI Pizza Rondo di Roma 450g  Saturday  supermarket       Okay     1
3         almond milk                         CAR DR. AMANDEL 1L  Saturday  supermarket  Carrefour     1
4                fish                          DISC KABELJAUWFIL  Saturday  supermarket  Carrefour     1
1             ketchup                         ZEIS KETCHUP 425ML  Saturday  supermarket  Carrefour     1
274              leek                                   prei Los  Saturday  supermarket       Okay     1
256     spring onions                            lenteuitjes bot  Saturday  supermarket       Okay     1
23        fish spread                            CV RIV KREEFTVL  Saturday  supermarket  Carrefour     1
262            salmon  EVERYDAY zalmfil. at. z. grat. ASC 2x125g  Saturday  supermarket       Okay     2
253          broccoli                          broccoli 1st 500g  Saturday  supermarket       Okay     1
19               eggs                         SIMPL SCHAR EI X12  Saturday  supermarket  Carrefour     1
18       cream cheese                           CAR RICOTTA 250G  Saturday  supermarket  Carrefour     1
269  carrots and peas          HAK erwt wortelen extra fijn 680g  Saturday  supermarket       Okay     1
245           pudding     JOYVALLE pudding griesmeel natuur 135g  Saturday  supermarket       Okay     2

     item_type      item_name        day    store_type     store_name     amount
39   charcuterie        FRIKANDON    Sunday   butcher   Versavel Poelman     1
38   fish spread    NEPTUNESALADA    Sunday   butcher   Versavel Poelman     1
208  charcuterie         KIPFILET    Monday   butcher   Versavel Poelman     1
36   meat spread        KIPSALADE    Sunday   butcher   Versavel Poelman     1
130  charcuterie    chateaubriand  Thursday   butcher              Brabo     1
203  meat spread  PREPARE DU CHEF    Monday   butcher   Versavel Poelman     1
41   charcuterie      DROGE WORST    Sunday   butcher   Versavel Poelman     1

    item_type     item_name        day    store_type store_name  amount
279    bread   GROF BROOD GESN.  Saturday   bakery       Sys        1